import { AlertTriangle, CheckCircle2, Info } from 'lucide-react';
import type { PredictionResponse } from '@/services/api';
import { ConfidenceChart } from './ConfidenceChart';

interface Props { result: PredictionResponse }
export function PredictionResult({ result }: Props) {
  const isReal = result.prediction === 'REAL';
  return <section className={`result-card ${isReal ? 'result-real' : 'result-fake'}`} aria-live="polite">
    <div className="result-top"><div><p className="eyebrow">Analysis complete</p><h2>Your signal is <span>{result.prediction}</span></h2></div><div className="result-icon">{isReal ? <CheckCircle2 /> : <AlertTriangle />}</div></div>
    <div className="result-grid"><ConfidenceChart real={result.probabilities.REAL} fake={result.probabilities.FAKE} /><div className="probability-list"><div className="model-confidence"><span>Model confidence</span><strong>{result.confidence.toFixed(2)}%</strong></div><div className="prob-row"><span><i className="dot real-dot" />REAL</span><b>{result.probabilities.REAL.toFixed(2)}%</b></div><div className="prob-bar"><span style={{ width: `${result.probabilities.REAL}%` }} /></div><div className="prob-row"><span><i className="dot fake-dot" />FAKE</span><b>{result.probabilities.FAKE.toFixed(2)}%</b></div><div className="prob-bar fake-bar"><span style={{ width: `${result.probabilities.FAKE}%` }} /></div></div></div>
    <div className="disclaimer"><Info size={17} /><p>This prediction is generated by a machine-learning model based on patterns learned from its training data. It is not definitive proof that an article is true or false.</p></div>
  </section>;
}
